### PR TITLE
Adding a new TryLocally() wrapper for actions.

### PR DESCRIPTION
**Pull request by austinprete**
`TryLocally(trace: Set[actions.trace], retries: Int)` continues to retry **trace** (a set of actions) until it has reached the number of iterations specified by **retries**, at which point it will throw the exception rather than retry.

### CODE REVIEW

**Comment by austinprete** [comment]
One of the more useful use cases of this is to use it inside of a Try() block. By doing so an action such as `Try(TryLocally(Wget("'{_}"), 2), 6)` can be created which will retry a failing action twice locally before moving it to another node in the cluster where it will again be tried twice before offloading the task to another node. 

Though this might seem slow, the advantage here is that a local retry is much quicker than a cluster-wise retry, so if the error can be resolved locally there is no need for the task to be retried on another node.

**Comment by tribbloid** [comment]
Oh actually all action traces are hardcoded to retried locally twice (I 
mean the entire linear trace, not a single action). But its common for 
users that want flexible retrying plan like 4x2 or 4x4, in the future we 
should try to avoid hardcoding, but this is not big deal.

**Comment by austinprete** [comment]
Ah interesting, so my example isn't useful with 2 as the number of local retries, but this would allow for more retries if desired

**Comment by austinprete** [comment]
@tribbloid Is this worth including then? And if so, is it fine in its current state?

**Comment by tribbloid** [comment]
Yes it is.

They serve different purpose: a trace always retries from the beginning. 
E.g. in Visit +> Click +> Snapshot if Click failed it will start over 
from Visit again, but Visit + Try(Click) will keep trying click an 
element in the same browser session. Should I merge it now?

**Comment by tribbloid** [comment]
Ah, sorry, the commit hasn't been ready, let me fix the maven deploy 
problem, this is irritating and blocking me from release.

**Comment by austinprete** [comment]
Yeah, feel free to merge it whenever

**Comment by tribbloid** [comment]
Thanks a lot! Merged

**Pull request merged**
